spring:
  datasource:
    url: jdbc:mysql://localhost:3306/h2test?createDatabaseIfNotExist=true
    username: root
    password: 12345
  jpa:
    hibernate:
      ddl-auto: update
  profiles:
    active:
      - dev









