spring:
  datasource:
    username: root
    password: 12345
    url: jdbc:mysql://localhost:3306/lasttime?createDatabaseIfNotExist=true
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update